# Generated by Django 6.0 on 2025-12-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_pic/')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
